### ISSUE TITLE
Missing model files

### ISSUE THREAD

**Issue by rscova** [mlherd/Dataset-of-Gazebo-Worlds-Models-and-Maps#1]
Hi,
I think in office world, there are some missing models: coffee_maker; dishwasher; conference_table_large; desk_chair; conference_table_small; computer and desk.
Thank you!

**Comment by mlherd** [comment]
Hi! Thanks for the heads up! I can't find the original repo for service sim world. It seems like it is not maintained anymore. Can you load the world? I will check if I have those models locally.

**Comment by mlherd** [comment]
Found the missing models :) I added them to part2.zip
